### ISSUE TITLE
Paper result recreation and use of own data

### ISSUE THREAD

**Issue by EyGy** [easton-cau/LeafMask#1]
Hi there,
thanks for your amazing work! I would love to replicate the results of your paper and eventually use LeafMask for my own dataset. Unfortunatley, I am not quite sure how to achieve this.

Can you help me with trying to get LeafMask up an running?
I am especially interested in your preferred working environment, the required data structure and how it is possible to training and inference with LSC and custom data.

Thank you in advance!

**Comment by easton-cau** [comment]
Thanks for your interest in our work. Our codes are based on detectron2==0.2.1 and AdelaiDet==0.2.0. Please learn these libraries before starting work.
